#!/usr/bin/env python3
# Copyright 2026 Anhang Li (AL-255, thelithcore@gmail.com)
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
#
# Read fpga/periph_split.config and emit the per-peripheral RTL(PL)/PS(A53) split:
#   * fpga/build/periph_split.vdefs  — the +define+VEN_<DEV>_PS flags for the RTL
#     build (a device with the macro defined is NOT synthesized into ventium_soc;
#     its I/O port range is forwarded over the AXI-Lite io-bridge to the A53).
#   * verif/tb/ps_periph_table.inc   — the C dispatch table (port range -> model)
#     consumed by tb_soc.cpp (verification) and the PS firmware (board), so the
#     io-bridge knows which C model in sw/ps_periph/ services each forwarded port.
#
# The default build passes NO VEN_<DEV>_PS, so the SoC is all-RTL and byte-identical
# to today. Run: python3 fpga/scripts/gen_periph_split.py
import os, sys, re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
CONFIG = os.path.join(ROOT, "fpga", "periph_split.config")

# Each device's I/O port range(s) + the macro/C-model name. Ranges are inclusive
# (lo, hi) tuples; a device may decode several disjoint ranges.
PERIPH = {
    "pic":    dict(macro="VEN_PIC_PS",   model="ven_pic",   ports=[(0x20,0x21),(0xA0,0xA1),(0x4D0,0x4D1)]),
    "pit":    dict(macro="VEN_PIT_PS",   model="ven_pit",   ports=[(0x40,0x43)]),
    "rtc":    dict(macro="VEN_RTC_PS",   model="ven_rtc",   ports=[(0x70,0x71)]),
    "i8042":  dict(macro="VEN_I8042_PS", model="ven_i8042", ports=[(0x60,0x60),(0x64,0x64)]),
    "port92": dict(macro="VEN_PORT92_PS",model="ven_port92",ports=[(0x92,0x92)]),
    "vga":    dict(macro="VEN_VGA_PS",   model="ven_vgaregs",ports=[(0x3B0,0x3DF)]),
    "acpipm": dict(macro="VEN_ACPIPM_PS",model="ven_acpipm",ports=[(0x608,0x608)]),
    "ide":    dict(macro="VEN_IDE_PS",   model="ven_ide",   ports=[(0x1F0,0x1F7),(0x3F6,0x3F6),(0x170,0x177),(0x376,0x376)]),
    "uart":   dict(macro="VEN_UART_PS",  model="ven_uart16550", ports=[(0x3F8,0x3FF)]),
    "dma":    dict(macro="VEN_DMA_PS",   model="ven_i8237", ports=[(0x00,0x0F),(0x81,0x83),(0x87,0x87)]),
    "dma2":   dict(macro="VEN_DMA2_PS",  model="ven_i8237b",ports=[(0xC0,0xDF),(0x89,0x8B),(0x8F,0x8F)]),
    "fdc":    dict(macro="VEN_FDC_PS",   model="ven_i8272", ports=[(0x3F1,0x3F5),(0x3F7,0x3F7)]),
}

def parse_config(path):
    placement = {}
    with open(path) as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) < 2:
                continue
            dev, place = parts[0], parts[1].lower()
            if dev not in PERIPH:
                sys.exit(f"unknown peripheral '{dev}' in {path}")
            if place not in ("rtl", "ps"):
                sys.exit(f"placement must be rtl|ps, got '{place}' for {dev}")
            placement[dev] = place
    return placement

def main():
    placement = parse_config(CONFIG)
    ps_devs = [d for d in PERIPH if placement.get(d) == "ps"]

    # 1. the +define+ flags for the RTL build
    os.makedirs(os.path.join(ROOT, "fpga", "build"), exist_ok=True)
    vdefs = os.path.join(ROOT, "fpga", "build", "periph_split.vdefs")
    with open(vdefs, "w") as f:
        f.write("// AUTO-GENERATED by gen_periph_split.py from fpga/periph_split.config\n")
        for d in PERIPH:
            if placement.get(d) == "ps":
                f.write(f"+define+{PERIPH[d]['macro']}\n")
        if not ps_devs:
            f.write("// (all peripherals in RTL/PL — default, no PS offload)\n")

    # 2. the C dispatch table (port range -> C model) for tb_soc / PS firmware
    inc = os.path.join(ROOT, "verif", "tb", "ps_periph_table.inc")
    with open(inc, "w") as f:
        f.write("// AUTO-GENERATED by gen_periph_split.py — do not edit.\n")
        f.write("// PS-placed peripheral port ranges -> C model (sw/ps_periph/<model>.c).\n")
        f.write("// { dev, model_ctor, port_lo, port_hi }\n")
        f.write("static const ps_periph_entry_t PS_PERIPH_TABLE[] = {\n")
        for d in ps_devs:
            for lo, hi in PERIPH[d]["ports"]:
                f.write(f'    {{ "{d}", {PERIPH[d]["model"]}_new, 0x{lo:04X}, 0x{hi:04X} }},\n')
        f.write("    { 0, 0, 0, 0 }\n};\n")

    print(f"peripheral split: {len(ps_devs)} on PS ({', '.join(ps_devs) or 'none'}), "
          f"{len(PERIPH)-len(ps_devs)} in RTL/PL")
    print(f"  wrote {os.path.relpath(vdefs, ROOT)}")
    print(f"  wrote {os.path.relpath(inc, ROOT)}")
    for d in ps_devs:
        c = os.path.join(ROOT, "sw", "ps_periph", PERIPH[d]["model"] + ".c")
        print(f"    PS {d:8s} -> {PERIPH[d]['model']}.c " +
              ("(present)" if os.path.exists(c) else "(MISSING — needs a C model)"))

if __name__ == "__main__":
    main()
